report:
  description: |
    This report returns information from the `meta` collection where all objects across all platforms is stored. The meta
    collection is used to find an object based on its platform, collection, collection id.
  headers:
    - Active
    - Platform
    - Service
    - Type
    - Account
    - Region
    - UniqueIdentifier
    - Location
    - LastSeen
    - DeactivatedOn

  tasks:
    - mongo:
        name: get meta collection
        collection: metadata
        silo: harvest-core
        filters: '.*'
        result_as: result

        arguments:
          pipeline:
            - $project:
                Active: "$Active"
                Platform: "$Platform"
                Service: "$Service"
                Type: "$Type"
                Account: "$Account"
                Region: "$Region"
                Location:
                  $concat:
                    - "$Silo.Name"
                    - "/"
                    - "$Silo.Collection"
                UniqueIdentifier: "$UniqueIdentifier"
                LastSeen: "$Dates.LastSeen"
                DeactivatedOn: "$Dates.DeactivatedOn"
